import time
import operator
import os
from typing import Annotated, TypedDict, List
from langgraph.graph import StateGraph, START, END
from langgraph.types import Send
from langchain_core.messages import SystemMessage, HumanMessage

# Optional imports for different models
try:
    from langchain_google_genai import ChatGoogleGenerativeAI
except ImportError:
    pass

try:
    from langchain_openai import ChatOpenAI
except ImportError:
    pass

try:
    from langchain_anthropic import ChatAnthropic
except ImportError:
    pass

def get_llm(provider="gemini"):
    """Toggle between different LLM providers."""
    if provider == "gemini":
        # Ensure GOOGLE_API_KEY is set
        return ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)
    elif provider == "openai":
        # Ensure OPENAI_API_KEY is set
        return ChatOpenAI(model="gpt-4o-mini", temperature=0)
    elif provider == "anthropic":
        # Ensure ANTHROPIC_API_KEY is set
        return ChatAnthropic(model="claude-3-haiku-20240307", temperature=0)
    else:
        raise ValueError(f"Unknown provider: {provider}")

# We'll use Gemini by default as configured
llm = get_llm("gemini")

# --- 1. State Definitions ---

class SequentialState(TypedDict):
    task_goal: str
    plan: List[str] # Tasks remaining
    completed_steps: Annotated[List[str], operator.add]
    generated_code: Annotated[List[str], operator.add]
    total_tokens: Annotated[int, operator.add]

class DistributedState(TypedDict):
    task_goal: str
    plan: List[str]
    generated_code: Annotated[List[str], operator.add]
    total_tokens: Annotated[int, operator.add]

class ScatterGatherState(TypedDict):
    task_goal: str
    plan: List[str]
    generated_code: Annotated[List[str], operator.add]
    total_tokens: Annotated[int, operator.add]
    final_synthesis: str
    
# State for a single parallel worker
class WorkerState(TypedDict):
    task_description: str
    task_goal: str

# --- 2. Shared Nodes ---

def parallel_worker(state: WorkerState):
    # Execute with LLM 
    messages = [
        SystemMessage(content=f"You are a coding assistant. Your overall goal is: {state['task_goal']}"),
        HumanMessage(content=f"Please implement this specific step: {state['task_description']}\nReturn ONLY the code.")
    ]
    response = llm.invoke(messages)
    tokens = response.usage_metadata.get("total_tokens", 0) if response.usage_metadata else 0
    return {
        "generated_code": [response.content],
        "total_tokens": tokens
    }

# --- 3. Sequential Nodes ---

def sequential_worker(state: SequentialState):
    plan = state["plan"]
    if not plan:
        return {} # Should not happen if we route correctly
    
    current_task = plan[0]
    remaining_plan = plan[1:]
    
    messages = [
        SystemMessage(content=f"You are a coding assistant. Your overall goal is: {state['task_goal']}"),
        HumanMessage(content=f"Please implement this specific step: {current_task}\nReturn ONLY the code.")
    ]
    response = llm.invoke(messages)
    tokens = response.usage_metadata.get("total_tokens", 0) if response.usage_metadata else 0
    
    return {
        "plan": remaining_plan,
        "completed_steps": [current_task],
        "generated_code": [response.content],
        "total_tokens": tokens
    }

def sequential_router(state: SequentialState):
    if len(state["plan"]) == 0:
        return END
    return "worker"

# --- 4. Distributed / Scatter-Gather Nodes ---

def distributed_dispatcher(state: DistributedState): # Works for both Distributed and ScatterGather
    sends = []
    for task in state["plan"]:
        sends.append(
            Send("parallel_worker", {
                "task_description": task,
                "task_goal": state["task_goal"]
            })
        )
    return sends

def synthesize_node(state: ScatterGatherState):
    # This is the "Gather" step
    code_snippets = "\n\n--- snippet ---\n\n".join(state["generated_code"])
    messages = [
        SystemMessage(content=f"You are a tech lead. The overall goal is: {state['task_goal']}"),
        HumanMessage(content=f"Here are the code snippets generated by the parallel workers:\n{code_snippets}\n\nPlease synthesize them into one cohesive Python file.")
    ]
    response = llm.invoke(messages)
    tokens = response.usage_metadata.get("total_tokens", 0) if response.usage_metadata else 0
    
    return {
        "final_synthesis": response.content,
        "total_tokens": tokens
    }

# --- 5. Build Graphs ---

def build_sequential_graph():
    builder = StateGraph(SequentialState)
    builder.add_node("worker", sequential_worker)
    builder.add_edge(START, "worker")
    builder.add_conditional_edges("worker", sequential_router)
    return builder.compile()

def build_distributed_graph():
    builder = StateGraph(DistributedState)
    builder.add_node("parallel_worker", parallel_worker)
    builder.add_conditional_edges(START, distributed_dispatcher)
    # The Send API automatically routes back to END when all workers finish
    return builder.compile()

def build_scatter_gather_graph():
    builder = StateGraph(ScatterGatherState)
    builder.add_node("parallel_worker", parallel_worker)
    builder.add_node("synthesize_node", synthesize_node)
    
    # 1. Scatter
    builder.add_conditional_edges(START, distributed_dispatcher)
    # 2. Gather (Route all workers to the synthesize node when done)
    builder.add_edge("parallel_worker", "synthesize_node")
    # 3. End
    builder.add_edge("synthesize_node", END)
    
    return builder.compile()

# --- 6. Profiling Harness ---

def profile_run(graph, state_input, name: str):
    print(f"\n{'='*40}")
    print(f"--- Profiling {name} ---")
    print(f"{'='*40}")
    
    start_time = time.time()
    
    result = graph.invoke(state_input)
        
    end_time = time.time()
    elapsed = end_time - start_time
    total_tokens = result.get("total_tokens", 0)
    
    print(f"Time Taken: {elapsed:.2f} seconds")
    print(f"Total Tokens Used: {total_tokens}")
    print(f"Generated {len(result.get('generated_code', []))} blocks of code.")
    
    if "final_synthesis" in result:
        print("\nFinal Synthesis Preview:")
        preview = result["final_synthesis"][:200] + "..." if len(result["final_synthesis"]) > 200 else result["final_synthesis"]
        print(preview)
        
    return result

if __name__ == "__main__":
    if "GOOGLE_API_KEY" not in os.environ:
        print("WARNING: GOOGLE_API_KEY environment variable not set.")
        print("Please export it (e.g., `export GOOGLE_API_KEY='AIza...'`) before running to get real results.")
    
    # Example manual plan
    task_goal = "Build a simple math library with unit tests."
    plan = [
        "Write an addition function in python.",
        "Write a subtraction function in python.",
        "Write a multiplication function in python.",
        "Write a division function in python."
    ]
    
    print(f"Goal: {task_goal}")
    print(f"Tasks in Plan: {len(plan)}")
    
    # 1. Profile Sequential
    seq_graph = build_sequential_graph()
    seq_state = {"task_goal": task_goal, "plan": plan}
    profile_run(seq_graph, seq_state, "Sequential Plan")
    
    # 2. Profile Distributed
    dist_graph = build_distributed_graph()
    dist_state = {"task_goal": task_goal, "plan": plan}
    profile_run(dist_graph, dist_state, "Distributed Plan")
    
    # 3. Profile Scatter-Gather
    sg_graph = build_scatter_gather_graph()
    sg_state = {"task_goal": task_goal, "plan": plan}
    profile_run(sg_graph, sg_state, "Scatter-Gather Plan")