"""Grade completed runs on two deliverables per run:

  mechanical (primary)  git diff of files_after/ - the workspace state the
                        agents actually produced - against the base commit,
                        with files touched by the gold test patch excluded.
                        Generated by git, needs no repair, and reflects the
                        state that coordination events act on.
  emitted (secondary)   the unified diff the final node wrote from memory.
                        Kept for comparison; grading it alone conflates
                        diff-fabrication ability with task outcome.

Axes, identical for both deliverables:
  resolved   every FAIL_TO_PASS test passes (binary)
  test_frac  fraction of FAIL_TO_PASS tests passing, run one at a time
  content    fraction of the task rubric present in the patch text
  stage      the 0-4 ladder, kept in grades.json for the record; for the
             mechanical deliverable stages 1-2 are dead by construction
             (git generated the diff at the base commit; gold-test files
             were excluded), so it carries no information beyond
             workspace-exists (>=3) vs not (0)

grades.json: top-level fields are the mechanical grade; the emitted grade
is nested under "emitted". The stage/content composite ("overall") is
dropped: resolved and test_frac replace it. Raw artifacts are never
modified; the mechanical diff is saved as patch.mechanical.diff and the
repaired emitted diff as patch.normalized.diff (repairs logged).

Usage:
  python scripts/grade.py                          # all non-mock runs
  python scripts/grade.py --python C:\\py38\\python.exe   # + stage-4 test runs
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"

# pytest repos list bare test names in FAIL_TO_PASS; map name -> file.
# django-style repos need no mapping (ids carry the module path).
PYTEST_F2P_FILES = {
    "sympy__sympy-18087": {
        "test_Factors": "sympy/core/tests/test_exprtools.py",
        "test_fu": "sympy/simplify/tests/test_fu.py",
    },
}


def f2p_commands(task: str):
    """[(test_id, argv)] - one interpreter invocation per FAIL_TO_PASS test,
    so each test yields its own pass/fail via the return code."""
    ids = json.loads((ROOT / "tasks" / task / "gold" / "tests.json")
                     .read_text(encoding="utf-8"))["FAIL_TO_PASS"]
    cmds = []
    if task.startswith("django__"):
        for tid in ids:
            m = re.match(r"(\S+) \((\S+)\)", tid)
            target = f"{m.group(2)}.{m.group(1)}" if m else tid
            cmds.append((tid, ["tests/runtests.py", target,
                               "--parallel", "1"]))
        return cmds
    files = PYTEST_F2P_FILES[task]
    for tid in ids:
        cmds.append((tid, ["-m", "pytest", f"{files[tid]}::{tid}",
                           "-p", "no:cacheprovider", "-q"]))
    return cmds

# (regex on the patch text, minimum count). content = mean of min(1, n/min).
RUBRICS = {
    "django__django-11099": [
        (re.escape(r"\A[\w.@+-]+\Z"), 2),
    ],
    "sympy__sympy-18087": [
        (re.escape("sympy/core/exprtools.py"), 1),
    ],
    "django__django-11019": [
        (re.escape("django/forms/widgets.py"), 1),
        (r"\n\+[^\n]*merge", 1),
    ],
    # authored Figure-1 task: the two anchors are the shared-fixture regions
    # owned by t1 (a_signal) and t2 (c_signal); a lost update on the shared
    # test file removes exactly one of them, grading content 0.5
    "django__providing-args": [
        (r"\n-a_signal = Signal\(providing_args", 1),
        (r"\n-c_signal = Signal\(providing_args", 1),
    ],
}


def sh(args, cwd=None, env=None):
    try:
        return subprocess.run(args, cwd=cwd, capture_output=True,
                              text=True, encoding="utf-8", errors="replace",
                              env=env, timeout=600)
    except subprocess.TimeoutExpired:
        r = subprocess.CompletedProcess(args, returncode=124,
                                        stdout="", stderr="timeout")
        return r


def wtext(path: Path, text: str):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def normalize(raw: str) -> str:
    raw = raw.replace("\r\n", "\n")
    norm = re.sub(r"^```[a-z]*\s*\n", "", raw.strip())
    norm = re.sub(r"\n```\s*$", "", norm)
    return norm + ("" if norm.endswith("\n") else "\n")


def content_score(task: str, patch_text: str) -> float:
    rubric = RUBRICS.get(task, [])
    if not rubric or not patch_text.strip():
        return 0.0
    parts = [min(1.0, len(re.findall(p, patch_text)) / need)
             for p, need in rubric]
    return round(sum(parts) / len(parts), 2)


def gold_test_files(task: str) -> set:
    text = (ROOT / "tasks" / task / "gold" / "test_patch.diff").read_text(
        encoding="utf-8")
    return set(re.findall(r"^diff --git a/(\S+)", text, re.MULTILINE))


def mechanical_diff(run_dir: Path, task: str):
    """git diff of files_after/ against the base commit.

    Files the gold test patch touches are excluded before diffing, so the
    grade reflects the model's source edits and the gold test patch always
    supplies the tests. Returns (diff_text or None, excluded_paths).
    """
    after = run_dir / "files_after"
    repo = ROOT / "tasks" / task / "repo"
    if not after.is_dir():
        return None, []
    excluded = gold_test_files(task)
    files = [f for f in sorted(after.rglob("*")) if f.is_file()]
    if not files:
        return None, []
    skipped = []
    with tempfile.TemporaryDirectory() as tmp:
        wt = Path(tmp) / "wt"
        if sh(["git", "worktree", "add", "--detach", str(wt)],
              cwd=repo).returncode != 0:
            return None, []
        try:
            copied = 0
            for f in files:
                rel = f.relative_to(after).as_posix()
                if rel in excluded:
                    skipped.append(rel)
                    continue
                dest = wt / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                wtext(dest, f.read_text(encoding="utf-8"))
                copied += 1
            if copied == 0:
                return None, skipped
            sh(["git", "add", "-A"], cwd=wt)
            r = sh(["git", "diff", "--cached", "--no-color"], cwd=wt)
            if r.returncode != 0 or not r.stdout.strip():
                return None, skipped
            return r.stdout, skipped
        finally:
            sh(["git", "worktree", "remove", "--force", str(wt)], cwd=repo)
            sh(["git", "worktree", "prune"], cwd=repo)


def ladder(task: str, patch_path: Path, python_exe, run_dir: Path,
           label: str) -> dict:
    """Run one patch file up the stage ladder. patch_path must exist."""
    repo = ROOT / "tasks" / task / "repo"
    gold_tests = ROOT / "tasks" / task / "gold" / "test_patch.diff"
    row = {"stage": 1, "content": 0.0, "applies": False,
           "test_patch_applies": False, "resolved": False,
           "test_frac": None, "f2p_pass": None, "f2p_total": None,
           "tests": "n/a"}
    row["content"] = content_score(
        task, patch_path.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory() as tmp:
        wt = Path(tmp) / "wt"
        if sh(["git", "worktree", "add", "--detach", str(wt)],
              cwd=repo).returncode != 0:
            row["overall"] = round(row["stage"] / 4 * row["content"], 3)
            return row
        try:
            r = sh(["git", "apply", "--whitespace=nowarn",
                    str(patch_path.resolve())], cwd=wt)
            if r.returncode == 0:
                row["applies"] = True
                row["stage"] = 2
                r = sh(["git", "apply", "--whitespace=nowarn",
                        str(gold_tests.resolve())], cwd=wt)
                if r.returncode == 0:
                    row["test_patch_applies"] = True
                    row["stage"] = 3
                    if python_exe:
                        results, logs = [], []
                        for tid, argv in f2p_commands(task):
                            r = sh([python_exe] + argv, cwd=wt,
                                   env={**os.environ, "PYTHONPATH": str(wt)})
                            ok = r.returncode == 0
                            results.append((tid, ok))
                            logs.append(f"===== {tid}: "
                                        f"{'PASS' if ok else 'FAIL'} =====\n"
                                        + r.stdout
                                        + "\n--- stderr ---\n" + r.stderr)
                        passed = sum(1 for _, ok in results if ok)
                        total = len(results)
                        row["f2p_pass"], row["f2p_total"] = passed, total
                        row["test_frac"] = round(passed / total, 3) if total else 0.0
                        row["resolved"] = total > 0 and passed == total
                        row["tests"] = f"{passed}/{total}"
                        wtext(run_dir / f"test_output.{label}.txt",
                              "\n\n".join(logs))
                        if row["resolved"]:
                            row["stage"] = 4
                else:
                    row["apply_error"] = r.stderr.strip()[:200]
            else:
                row["apply_error"] = r.stderr.strip()[:200]
        finally:
            sh(["git", "worktree", "remove", "--force", str(wt)], cwd=repo)
            sh(["git", "worktree", "prune"], cwd=repo)
    return row


def grade_run(run_dir: Path, python_exe):
    task = run_dir.name.split(".")[0]
    row = {"run": run_dir.name, "task": task}

    # mechanical (primary)
    diff_text, excluded = mechanical_diff(run_dir, task)
    if diff_text is None:
        mech = {"stage": 0, "content": 0.0, "applies": False,
                "test_patch_applies": False, "resolved": False,
                "test_frac": None, "f2p_pass": None, "f2p_total": None,
                "tests": "no workspace"}
    else:
        mech_path = run_dir / "patch.mechanical.diff"
        wtext(mech_path, diff_text)
        mech = ladder(task, mech_path, python_exe, run_dir, "mechanical")
    row.update(mech)
    row["excluded_gold_test_files"] = excluded

    # emitted (secondary)
    raw_path = run_dir / "patch.diff"
    if not raw_path.exists() or not raw_path.read_text(
            encoding="utf-8").strip():
        row["emitted"] = {"stage": 0, "content": 0.0, "applies": False,
                          "test_patch_applies": False, "resolved": False,
                          "test_frac": None, "f2p_pass": None,
                          "f2p_total": None, "tests": "no patch"}
    else:
        norm_path = run_dir / "patch.normalized.diff"
        wtext(norm_path, normalize(raw_path.read_text(encoding="utf-8")))
        row["emitted"] = ladder(task, norm_path, python_exe, run_dir,
                                "emitted")
    return row


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--python", default=None)
    ap.add_argument("--runs", nargs="*", default=None)
    args = ap.parse_args()

    for task_dir in (ROOT / "tasks").iterdir():
        repo = task_dir / "repo"
        if repo.is_dir():
            sh(["git", "config", "core.autocrlf", "false"], cwd=repo)
            sh(["git", "config", "core.eol", "lf"], cwd=repo)

    if args.runs:
        dirs = [RUNS / r for r in args.runs if "--mock" not in r]
    else:
        dirs = sorted(d for d in RUNS.iterdir()
                      if d.is_dir() and "--mock" not in d.name)
    gfile = RUNS / "grades.json"
    merged = {}
    if gfile.exists():
        for r in json.loads(gfile.read_text(encoding="utf-8")):
            merged[r["run"]] = r
    if not args.runs:
        # full pass: every listed dir gets regraded, stale rows for
        # since-deleted runs are dropped
        merged = {k: v for k, v in merged.items()
                  if k in {d.name for d in dirs}}
    rows = []
    for i, d in enumerate(dirs, 1):
        print(f"[{i}/{len(dirs)}] {d.name} ...", flush=True)
        r = grade_run(d, args.python)
        rows.append(r)
        merged[r["run"]] = r
        # incremental write: progress survives interruption
        gfile.write_text(json.dumps(sorted(merged.values(),
                                           key=lambda x: x["run"]),
                                    indent=2), encoding="utf-8")
    w = max((len(r["run"]) for r in rows), default=10)
    print(f"{'run':<{w}}  {'ws':>2}  {'m.cont':>6}  {'m.f2p':>6}  "
          f"{'m.res':>5}  {'e.stage':>7}  {'e.cont':>6}  {'e.f2p':>6}")
    for r in rows:
        e = r["emitted"]
        ws = "y" if r["stage"] >= 3 else "n"
        print(f"{r['run']:<{w}}  {ws:>2}  {r['content']:>6}  "
              f"{r['tests']:>6}  {str(r['resolved']):>5}  "
              f"{e['stage']:>7}  {e['content']:>6}  {e['tests']:>6}")
    print("\nws = workspace diff exists; m.* = mechanical grade of "
          "files_after/ (primary); e.* = grade of the final node's "
          "emitted diff (secondary). wrote runs/grades.json")


if __name__ == "__main__":
    main()
