"""Failed-vs-clean structural comparison over ChatDev/ProgramDev plan-graphs.

Runs ``iter_chatdev`` over the full dataset (filtered to ProgramDev), splits
the traces into *failed* (any of the 14 MAST modes flagged) and *clean* (none
flagged), and compares structural metrics between the two groups. A second
table gives the same metrics per MAST category (1.x specification, 2.x
coordination, 3.x verification) over the traces flagged in that category.

The report is printed and written to docs/failed_vs_clean.md. Deterministic
(no timestamps): re-running yields byte-identical output. The only network
access is the cached download inside the loader.

Run from the repo root:
    python scripts/05_failed_vs_clean.py
"""
from __future__ import annotations

import statistics
import sys
from pathlib import Path
from typing import List, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from agent_guarantees.mad import loader  # noqa: E402
from agent_guarantees.mad.graph import iter_chatdev  # noqa: E402
from agent_guarantees.mad.loader import MAST_MODES  # noqa: E402

DOCS = ROOT / "docs"
OUT_FILE = DOCS / "failed_vs_clean.md"

BENCHMARK = "ProgramDev"
METRIC_KEYS = [
    "exchange_count", "write_count", "run_count",
    "node_count", "depth", "parallelizable_width",
]

# Group sizes observed in the prior manual analysis; a mismatch is not an
# error, but it means the corpus (or the extractor) drifted — warn loudly.
EXPECTED_FAILED = 93
EXPECTED_CLEAN = 37

CATEGORIES = [
    ("Specification (1.x)", "1."),
    ("Coordination (2.x)", "2."),
    ("Verification (3.x)", "3."),
]


def _render_table(headers: Sequence[str], rows: Sequence[Sequence]) -> str:
    cells = [[str(c) for c in row] for row in rows]
    widths = [
        max([len(str(headers[i]))] + [len(row[i]) for row in cells])
        for i in range(len(headers))
    ]

    def line(values: Sequence[str]) -> str:
        return "| " + " | ".join(str(v).ljust(widths[i]) for i, v in enumerate(values)) + " |"

    out = [line(headers), "| " + " | ".join("-" * widths[i] for i in range(len(headers))) + " |"]
    out.extend(line(row) for row in cells)
    return "\n".join(out)


# --- split + aggregation (each returns plain data; no I/O) ----------------
def is_failed(record: dict) -> bool:
    """True when any of the 14 MAST modes is flagged on the record."""
    return any(record["mast_flags"].get(mode, 0) for mode in MAST_MODES)


def in_category(record: dict, prefix: str) -> bool:
    """True when any flagged mode falls in the category (e.g. prefix "2.")."""
    return any(
        value and mode.startswith(prefix)
        for mode, value in record["mast_flags"].items()
    )


def split_failed_clean(records: Sequence[dict]) -> Tuple[List[dict], List[dict]]:
    """Split extract_record dicts into (failed, clean) by their mast_flags."""
    failed = [r for r in records if is_failed(r)]
    clean = [r for r in records if not is_failed(r)]
    return failed, clean


def _mean_median(group: Sequence[dict], key: str) -> Tuple[str, str]:
    """Formatted (mean, median) of one metric over a group; "-" when empty."""
    values = [r["metrics"][key] for r in group]
    if not values:
        return "-", "-"
    return f"{statistics.mean(values):.2f}", f"{statistics.median(values):.1f}"


def aggregate_rows(failed: Sequence[dict], clean: Sequence[dict]) -> List[list]:
    """Rows of (metric, failed mean, failed median, clean mean, clean median)."""
    rows = []
    for key in METRIC_KEYS:
        f_mean, f_median = _mean_median(failed, key)
        c_mean, c_median = _mean_median(clean, key)
        rows.append([key, f_mean, f_median, c_mean, c_median])
    return rows


def category_rows(records: Sequence[dict]) -> List[list]:
    """Rows of (category, n, metric, mean, median) for the three categories."""
    rows = []
    for label, prefix in CATEGORIES:
        group = [r for r in records if in_category(r, prefix)]
        for key in METRIC_KEYS:
            mean, median = _mean_median(group, key)
            rows.append([label, len(group), key, mean, median])
    return rows


# --- report assembly -------------------------------------------------------
def build_report(records: Sequence[dict]) -> str:
    failed, clean = split_failed_clean(records)

    sections: List[str] = []

    sections.append(
        "# Failed vs clean structural comparison (ChatDev/ProgramDev)\n\n"
        "Generated by `scripts/05_failed_vs_clean.py` from the cached MAD "
        "files. Deterministic (no timestamps): re-run to regenerate.\n\n"
        "*Failed* = any of the 14 MAST modes flagged; *clean* = none flagged."
    )

    size_lines = [
        f"- Failed traces: {len(failed)}",
        f"- Clean traces: {len(clean)}",
        f"- Total: {len(records)}",
    ]
    if len(failed) != EXPECTED_FAILED or len(clean) != EXPECTED_CLEAN:
        size_lines.append(
            f"\nWARNING: group sizes {len(failed)}/{len(clean)} differ from "
            f"the {EXPECTED_FAILED}/{EXPECTED_CLEAN} of the prior manual "
            "analysis — the corpus or the extractor drifted."
        )
    sections.append(
        "## 1. Group sizes and aggregate metrics\n\n"
        + "\n".join(size_lines)
        + "\n\n"
        + _render_table(
            ["Metric", "Failed mean", "Failed median", "Clean mean", "Clean median"],
            aggregate_rows(failed, clean),
        )
    )

    sections.append(
        "## 2. Per-MAST-category split\n\n"
        "Same metrics over the traces flagged in each category (a trace "
        "flagged in several categories appears in each):\n\n"
        + _render_table(
            ["Category", "N", "Metric", "Mean", "Median"],
            category_rows(records),
        )
    )

    return "\n\n".join(sections) + "\n"


def main() -> None:
    records = list(iter_chatdev(loader, benchmarks=BENCHMARK))

    report = build_report(records)
    print(report)

    DOCS.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(report, encoding="utf-8")
    print(f"\nWrote {OUT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
